### ISSUE TITLE
nameko-kafka 0.2.0 requires wrapt==1.11,  This dependency makes our pipenv fail as other packages require higher version of wrapt

### ISSUE THREAD

**Issue by jaysar2011** [ketgo/nameko-kafka#4]
Is there a way to overcome wrapt package dependency for nameko-kafka?  How to get it installed keeping higher version of wrapt

**Comment by ketgo** [comment]
Apologies for the late reply. The explicit dependency on wrapt1.11 was introduced as it was needed by python-kafka the last time I made a commit. I believe this might no longer be true for the latest version of python-kafka so we can remove it. However I won't be able to work on investigation this anytime soon so would welcome a PR if you have time :)

**Comment by joaomcarlos** [comment]
Hi,

We are having the same issue. We have made a temp fix by doing the following: https://gist.github.com/joaomcarlos/8bbdf42ad0eb1dcfd0cf7291393dfeb6

However, this is ugly and prone to break often if it fails to run.

PS: will add a TODO for a pull request

**Comment by ketgo** [comment]
Thanks @joaomcarlos

**Comment by ketgo** [comment]
I have created a new PR (https://github.com/ketgo/nameko-kafka/pull/5) which removes the required wrapt dependency. Can I get someone to review it please.

**Comment by joaomcarlos** [comment]
Thanks @ketgo 

Just got back from holidays, we will review this fix shortly.

**Comment by joaomcarlos** [comment]
Hi again. I had a colleague review the PR and test it on our system. He approves of it, and he also approved the PR on GH!

**Comment by ketgo** [comment]
Thanks @joaomcarlos! Closing the issue.
